/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codeclause_url.shortener.project;

import java.util.HashMap;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class ShortenerWindow extends javax.swing.JFrame {
    
     HashMap<String,String> urlMap=new HashMap<>();
     String baseUrl="https://CodeClause/";

    /**
     * Creates new form SortenerWindow
     */
    public ShortenerWindow() {
        initComponents();
        setTitle("URL Shortener Application");
        ImageIcon icon=new ImageIcon(getClass().getResource("icon.png")); // Icon Source: www.icons8.com
        setIconImage(icon.getImage());
    }

    // Method to generate a random shortened URL code
    public String generateShortCode() {
        String chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        StringBuilder shortCode = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < 6; i++) { // 6-character short code
            shortCode.append(chars.charAt(random.nextInt(chars.length())));
        }
        return shortCode.toString();
    }

    // Method to shorten the given URL and store in the HashMap
    public String shortenUrl(String originalUrl) {
        if (originalUrl == null || originalUrl.isEmpty()) {
            throw new IllegalArgumentException("Original URL cannot be null or empty.");
        }

        String shortCode = generateShortCode();
        String shortenedUrl = this.baseUrl + shortCode;

        // Check if the generated short code is already in use, generate a new one if needed
        while (this.urlMap.containsKey(shortenedUrl)) {
            shortCode = generateShortCode();
            shortenedUrl = this.baseUrl + shortCode;
        }

        // Store the original URL and the shortened URL in the HashMap
        this.urlMap.put(shortenedUrl, originalUrl);
        return shortenedUrl;
    }

    // Method to get the original URL from the shortened URL
    public String getOriginalUrl(String shortenedUrl) {
        if (shortenedUrl == null || shortenedUrl.isEmpty()) {
            throw new IllegalArgumentException("Shortened URL cannot be null or empty.");
        }
        return this.urlMap.get(shortenedUrl);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        URL_TextField = new javax.swing.JTextField();
        ShortenButton = new javax.swing.JButton();
        ExtendButton = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Enter URL");

        URL_TextField.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        ShortenButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ShortenButton.setText("Shorten URL");
        ShortenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShortenButtonActionPerformed(evt);
            }
        });

        ExtendButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ExtendButton.setText("Extend URL");
        ExtendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtendButtonActionPerformed(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Label2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label2)
                    .addComponent(Label1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ShortenButton)
                        .addGap(53, 53, 53)
                        .addComponent(ExtendButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(URL_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(URL_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShortenButton)
                    .addComponent(ExtendButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label2)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShortenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShortenButtonActionPerformed
        String OriginalUrl=URL_TextField.getText();
        String ShortenedUrl=this.shortenUrl(OriginalUrl);
        Label1.setText("Original URL: " + OriginalUrl);
        Label2.setText("Shortened URL: " + ShortenedUrl);
        URL_TextField.setText("");
    }//GEN-LAST:event_ShortenButtonActionPerformed

    private void ExtendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtendButtonActionPerformed
        String ShortenedUrl=URL_TextField.getText();
        String OriginalUrl=this.getOriginalUrl(ShortenedUrl);
        Label1.setText("Shortened URL: " + ShortenedUrl);
        Label2.setText("Original URL: " + OriginalUrl);
        URL_TextField.setText("");

    }//GEN-LAST:event_ExtendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShortenerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShortenerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShortenerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShortenerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShortenerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExtendButton;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JButton ShortenButton;
    private javax.swing.JTextField URL_TextField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
